package fr.dva.model;

import com.fasterxml.jackson.annotation.JsonValue;

public enum Pays {
	//@formatter:off
	AFG("004","AF","AFG","Afghanistan (l')"),
	ZAF("710","ZA","ZAF","Afrique du Sud (l')"),
	ALA("248","AX","ALA","Åland(les Îles)"),
	ALB("008","AL","ALB","Albanie (l')"),
	DZA("012","DZ","DZA","Algérie (l')"),
	DEU("276","DE","DEU","Allemagne (l')"),
	AND("020","AD","AND","Andorre (l')"),
	AGO("024","AO","AGO","Angola (l')"),
	AIA("660","AI","AIA","Anguilla"),
	ATA("010","AQ","ATA","Antarctique (l')"),
	ATG("028","AG","ATG","Antigua-et-Barbuda"),
	SAU("682","SA","SAU","Arabie saoudite (l')"),
	ARG("032","AR","ARG","Argentine (l')"),
	ARM("051","AM","ARM","Arménie (l')"),
	ABW("533","AW","ABW","Aruba"),
	AUS("036","AU","AUS","Australie (l')"),
	AUT("040","AT","AUT","Autriche (l')"),
	AZE("031","AZ","AZE","Azerbaïdjan (l')"),
	BHS("044","BS","BHS","Bahamas (les)"),
	BHR("048","BH","BHR","Bahreïn"),
	BGD("050","BD","BGD","Bangladesh (le)"),
	BRB("052","BB","BRB","Barbade (la)"),
	BLR("112","BY","BLR","Bélarus (le)"),
	BEL("056","BE","BEL","Belgique (la)"),
	BLZ("084","BZ","BLZ","Belize (le)"),
	BEN("204","BJ","BEN","Bénin (le)"),
	BMU("060","BM","BMU","Bermudes (les)"),
	BTN("064","BT","BTN","Bhoutan (le)"),
	BOL("068","BO","BOL","Bolivie (État plurinational de)"),
	BES("535","BQ","BES","Bonaire, Saint-Eustache et Saba"),
	BIH("070","BA","BIH","Bosnie-Herzégovine (la)"),
	BWA("072","BW","BWA","Botswana (le)"),
	BVT("074","BV","BVT","Bouvet (l'Île)"),
	BRA("076","BR","BRA","Brésil (le)"),
	BRN("096","BN","BRN","Brunéi Darussalam (le)"),
	BGR("100","BG","BGR","Bulgarie (la)"),
	BFA("854","BF","BFA","Burkina Faso (le)"),
	BDI("108","BI","BDI","Burundi (le)"),
	CPV("132","CV","CPV","Cabo Verde"),
	CYM("136","KY","CYM","Caïmans (les Îles)"),
	KHM("116","KH","KHM","Cambodge (le)"),
	CMR("120","CM","CMR","Cameroun (le)"),
	CAN("124","CA","CAN","Canada (le)"),
	CHL("152","CL","CHL","Chili (le)"),
	CHN("156","CN","CHN","Chine (la)"),
	CXR("162","CX","CXR","Christmas (l'Île)"),
	CYP("196","CY","CYP","Chypre"),
	CCK("166","CC","CCK","Cocos (les Îles)/ Keeling (les Îles)"),
	COL("170","CO","COL","Colombie (la)"),
	COM("174","KM","COM","Comores (les)"),
	COD("180","CD","COD","Congo (la République démocratique du)"),
	COG("178","CG","COG","Congo (le)"),
	COK("184","CK","COK","Cook (les Îles)"),
	KOR("410","KR","KOR","Corée (la République de)"),
	PRK("408","KP","PRK","Corée (la République populaire démocratique de)"),
	CRI("188","CR","CRI","Costa Rica (le)"),
	CIV("384","CI","CIV","Côte d'Ivoire (la)"),
	HRV("191","HR","HRV","Croatie (la)"),
	CUB("192","CU","CUB","Cuba"),
	CUW("531","CW","CUW","Curaçao"),
	DNK("208","DK","DNK","Danemark (le)"),
	DJI("262","DJ","DJI","Djibouti"),
	DOM("214","DO","DOM","dominicaine (la République)"),
	DMA("212","DM","DMA","Dominique (la)"),
	EGY("818","EG","EGY","Égypte (l')"),
	SLV("222","SV","SLV","El Salvador"),
	ARE("784","AE","ARE","Émirats arabes unis (les)"),
	ECU("218","EC","ECU","Équateur (l')"),
	ERI("232","ER","ERI","Érythrée (l')"),
	ESP("724","ES","ESP","Espagne (l')"),
	EST("233","EE","EST","Estonie (l')"),
	SWZ("748","SZ","SWZ","Eswatini (l')"),
	USA("840","US","USA","États-Unis d'Amérique (les)"),
	ETH("231","ET","ETH","Éthiopie (l')"),
	FLK("238","FK","FLK","Falkland (les Îles)/Malouines (les Îles)"),
	FRO("234","FO","FRO","Féroé (les Îles)"),
	FJI("242","FJ","FJI","Fidji (les)"),
	FIN("246","FI","FIN","Finlande (la)"),
	FRA("250","FR","FRA","France (la)"),
	GAB("266","GA","GAB","Gabon (le)"),
	GMB("270","GM","GMB","Gambie (la)"),
	GEO("268","GE","GEO","Géorgie (la)"),
	SGS("239","GS","SGS","Géorgie du Sud-et-les Îles Sandwich du Sud (la)"),
	GHA("288","GH","GHA","Ghana (le)"),
	GIB("292","GI","GIB","Gibraltar"),
	GRC("300","GR","GRC","Grèce (la)"),
	GRD("308","GD","GRD","Grenade (la)"),
	GRL("304","GL","GRL","Groenland (le)"),
	GLP("312","GP","GLP","Guadeloupe (la)"),
	GUM("316","GU","GUM","Guam"),
	GTM("320","GT","GTM","Guatemala (le)"),
	GGY("831","GG","GGY","Guernesey"),
	GIN("324","GN","GIN","Guinée (la)"),
	GNQ("226","GQ","GNQ","Guinée équatoriale (la)"),
	GNB("624","GW","GNB","Guinée-Bissau (la)"),
	GUY("328","GY","GUY","Guyana (le)"),
	GUF("254","GF","GUF","Guyane française (la )"),
	HTI("332","HT","HTI","Haïti"),
	HMD("334","HM","HMD","Heard-et-Îles MacDonald (l'Île)"),
	HND("340","HN","HND","Honduras (le)"),
	HKG("344","HK","HKG","Hong Kong"),
	HUN("348","HU","HUN","Hongrie (la)"),
	IMN("833","IM","IMN","Île de Man"),
	UMI("581","UM","UMI","Îles mineures éloignées des États-Unis (les)"),
	IND("356","IN","IND","Inde (l')"),
	IOT("086","IO","IOT","Indien (le Territoire britannique de l'océan)"),
	IDN("360","ID","IDN","Indonésie (l')"),
	IRN("364","IR","IRN","Iran (République Islamique d')"),
	IRQ("368","IQ","IRQ","Iraq (l')"),
	IRL("372","IE","IRL","Irlande (l')"),
	ISL("352","IS","ISL","Islande (l')"),
	ISR("376","IL","ISR","Israël"),
	ITA("380","IT","ITA","Italie (l')"),
	JAM("388","JM","JAM","Jamaïque (la)"),
	JPN("392","JP","JPN","Japon (le)"),
	JEY("832","JE","JEY","Jersey"),
	JOR("400","JO","JOR","Jordanie (la)"),
	KAZ("398","KZ","KAZ","Kazakhstan (le)"),
	KEN("404","KE","KEN","Kenya (le)"),
	KGZ("417","KG","KGZ","Kirghizistan (le)"),
	KIR("296","KI","KIR","Kiribati"),
	KWT("414","KW","KWT","Koweït (le)"),
	LAO("418","LA","LAO","Lao (la République démocratique populaire)"),
	LSO("426","LS","LSO","Lesotho (le)"),
	LVA("428","LV","LVA","Lettonie (la)"),
	LBN("422","LB","LBN","Liban (le)"),
	LBR("430","LR","LBR","Libéria (le)"),
	LBY("434","LY","LBY","Libye (la)"),
	LIE("438","LI","LIE","Liechtenstein (le)"),
	LTU("440","LT","LTU","Lituanie (la)"),
	LUX("442","LU","LUX","Luxembourg (le)"),
	MAC("446","MO","MAC","Macao"),
	MKD("807","MK","MKD","Macédoine du Nord (la)"),
	MDG("450","MG","MDG","Madagascar"),
	MYS("458","MY","MYS","Malaisie (la)"),
	MWI("454","MW","MWI","Malawi (le)"),
	MDV("462","MV","MDV","Maldives (les)"),
	MLI("466","ML","MLI","Mali (le)"),
	MLT("470","MT","MLT","Malte"),
	MNP("580","MP","MNP","Mariannes du Nord (les Îles)"),
	MAR("504","MA","MAR","Maroc (le)"),
	MHL("584","MH","MHL","Marshall (les Îles)"),
	MTQ("474","MQ","MTQ","Martinique (la)"),
	MUS("480","MU","MUS","Maurice"),
	MRT("478","MR","MRT","Mauritanie (la)"),
	MYT("175","YT","MYT","Mayotte"),
	MEX("484","MX","MEX","Mexique (le)"),
	FSM("583","FM","FSM","Micronésie (États fédérés de)"),
	MDA("498","MD","MDA","Moldova (la République de)"),
	MCO("492","MC","MCO","Monaco"),
	MNG("496","MN","MNG","Mongolie (la)"),
	MNE("499","ME","MNE","Monténégro (le)"),
	MSR("500","MS","MSR","Montserrat"),
	MOZ("508","MZ","MOZ","Mozambique (le)"),
	MMR("104","MM","MMR","Myanmar (le)"),
	NAM("516","NA","NAM","Namibie (la)"),
	NRU("520","NR","NRU","Nauru"),
	NPL("524","NP","NPL","Népal (le)"),
	NIC("558","NI","NIC","Nicaragua (le)"),
	NER("562","NE","NER","Niger (le)"),
	NGA("566","NG","NGA","Nigéria (le)"),
	NIU("570","NU","NIU","Niue"),
	NFK("574","NF","NFK","Norfolk (l'Île)"),
	NOR("578","NO","NOR","Norvège (la)"),
	NCL("540","NC","NCL","Nouvelle-Calédonie (la)"),
	NZL("554","NZ","NZL","Nouvelle-Zélande (la)"),
	OMN("512","OM","OMN","Oman"),
	UGA("800","UG","UGA","Ouganda (l')"),
	UZB("860","UZ","UZB","Ouzbékistan (l')"),
	PAK("586","PK","PAK","Pakistan (le)"),
	PLW("585","PW","PLW","Palaos (les)"),
	PSE("275","PS","PSE","Palestine, État de"),
	PAN("591","PA","PAN","Panama (le)"),
	PNG("598","PG","PNG","Papouasie-Nouvelle-Guinée (la)"),
	PRY("600","PY","PRY","Paraguay (le)"),
	NLD("528","NL","NLD","Pays-Bas (les)"),
	PER("604","PE","PER","Pérou (le)"),
	PHL("608","PH","PHL","Philippines (les)"),
	PCN("612","PN","PCN","Pitcairn"),
	POL("616","PL","POL","Pologne (la)"),
	PYF("258","PF","PYF","Polynésie française (la)"),
	PRI("630","PR","PRI","Porto Rico"),
	PRT("620","PT","PRT","Portugal (le)"),
	QAT("634","QA","QAT","Qatar (le)"),
	SYR("760","SY","SYR","République arabe syrienne (la)"),
	CAF("140","CF","CAF","République centrafricaine (la)"),
	REU("638","RE","REU","Réunion (La)"),
	ROU("642","RO","ROU","Roumanie (la)"),
	GBR("826","GB","GBR","Royaume-Uni de Grande-Bretagne et d'Irlande du Nord (le)"),
	RUS("643","RU","RUS","Russie (la Fédération de)"),
	RWA("646","RW","RWA","Rwanda (le)"),
	ESH("732","EH","ESH","Sahara occidental (le)*"),
	BLM("652","BL","BLM","Saint-Barthélemy"),
	SHN("654","SH","SHN","Sainte-Hélène, Ascension et Tristan da Cunha"),
	LCA("662","LC","LCA","Sainte-Lucie"),
	KNA("659","KN","KNA","Saint-Kitts-et-Nevis"),
	SMR("674","SM","SMR","Saint-Marin"),
	MAF("663","MF","MAF","Saint-Martin (partie française)"),
	SXM("534","SX","SXM","Saint-Martin (partie néerlandaise)"),
	SPM("666","PM","SPM","Saint-Pierre-et-Miquelon"),
	VAT("336","VA","VAT","Saint-Siège (le)"),
	VCT("670","VC","VCT","Saint-Vincent-et-les Grenadines"),
	SLB("090","SB","SLB","Salomon (les Îles)"),
	WSM("882","WS","WSM","Samoa (le)"),
	ASM("016","AS","ASM","Samoa américaines (les)"),
	STP("678","ST","STP","Sao Tomé-et-Principe"),
	SEN("686","SN","SEN","Sénégal (le)"),
	SRB("688","RS","SRB","Serbie (la)"),
	SYC("690","SC","SYC","Seychelles (les)"),
	SLE("694","SL","SLE","Sierra Leone (la)"),
	SGP("702","SG","SGP","Singapour"),
	SVK("703","SK","SVK","Slovaquie (la)"),
	SVN("705","SI","SVN","Slovénie (la)"),
	SOM("706","SO","SOM","Somalie (la)"),
	SDN("729","SD","SDN","Soudan (le)"),
	SSD("728","SS","SSD","Soudan du Sud (le)"),
	LKA("144","LK","LKA","Sri Lanka"),
	SWE("752","SE","SWE","Suède (la)"),
	CHE("756","CH","CHE","Suisse (la)"),
	SUR("740","SR","SUR","Suriname (le)"),
	SJM("744","SJ","SJM","Svalbard et l'Île Jan Mayen (le)"),
	TJK("762","TJ","TJK","Tadjikistan (le)"),
	TWN("158","TW","TWN","Taïwan (Province de Chine)"),
	TZA("834","TZ","TZA","Tanzanie (la République-Unie de)"),
	TCD("148","TD","TCD","Tchad (le)"),
	CZE("203","CZ","CZE","Tchéquie (la)"),
	ATF("260","TF","ATF","Terres australes françaises (les)"),
	THA("764","TH","THA","Thaïlande (la)"),
	TLS("626","TL","TLS","Timor-Leste (le)"),
	TGO("768","TG","TGO","Togo (le)"),
	TKL("772","TK","TKL","Tokelau (les)"),
	TON("776","TO","TON","Tonga (les)"),
	TTO("780","TT","TTO","Trinité-et-Tobago (la)"),
	TUN("788","TN","TUN","Tunisie (la)"),
	TKM("795","TM","TKM","Turkménistan (le)"),
	TCA("796","TC","TCA","Turks-et-Caïcos (les Îles)"),
	TUR("792","TR","TUR","Turquie (la)"),
	TUV("798","TV","TUV","Tuvalu (les)"),
	UKR("804","UA","UKR","Ukraine (l')"),
	URY("858","UY","URY","Uruguay (l')"),
	VUT("548","VU","VUT","Vanuatu (le)"),
	VEN("862","VE","VEN","Venezuela (République bolivarienne du)"),
	VGB("092","VG","VGB","Vierges britanniques (les Îles)"),
	VIR("850","VI","VIR","Vierges des États-Unis (les Îles)"),
	VNM("704","VN","VNM","Viet Nam (le)"),
	WLF("876","WF","WLF","Wallis-et-Futuna"),
	YEM("887","YE","YEM","Yémen (le)"),
	ZMB("894","ZM","ZMB","Zambie (la)"),
	ZWE("716","ZW","ZWE","Zimbabwe (le)");
	//@formatter:off


	private String numericCode;
	private String alpha2Code;
	private String alpha3Code;
	private String name;
	
	private Pays(final String numricCode, final String alpha2Code, final String alpha3Code, final String name) {
		this.numericCode = numricCode;
		this.alpha2Code = alpha2Code;
		this.alpha3Code = alpha3Code;
		this.name = name;
	}

	public String getNumericCode() {
		return numericCode;
	}

	public String getAlpha2Code() {
		return alpha2Code;
	}

	@JsonValue
	public String getAlpha3Code() {
		return alpha3Code;
	}

	public String getName() {
		return name;
	}
	
	
}
